apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: karpenter
spec:
  requirements:
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["on-demand"]
    - key: "karpenter.sh/instance-type"
      operator: In
      values: ["Standard_B2s", "Standard_D2s_v3", "Standard_D4_v3"]
  limits:
    resources:
      cpu: "1000"
      memory: "2000Gi"
  providerRef:
    name: default
